CloudCoreo/default-panel

index.html
js/audit.js
js/script.js
js/static-map.js
tmp-data/tmp.json

PlA-1817, PLA-1815 solved.
Bug with links for passed violation is fixed.

Pla 1817 bug fixing

---

js/audit.js
js/deploy.js
tmp-data/tmp.json

Fix for duplicated data on panels when ccthis updated.
Fix for bug  when violation is recognized as passed, but really it is not

Pla 1863 fix for panel duplicates

---

css/audit.css
css/common.css

PLA-2117 - Fixed panel absence on Safari.
PLA-2208 - padding was added to the "XX-violations"

PLA-2208 - Padding added to the "XX violation".

---

css/audit.css
css/deploy.css
index.html

It won't work until PLA-2200 branch on webapp is not merged.

PLA-2200 - Deploy tab has sticky table header now.

---

css/audit.css
js/audit.js
js/script.js

Pla 2338 ui fixes

---

css/audit.css
index.html
js/deploy.js
js/script.js
tmp-data/tmp1.json

Resources from previous execution are displayed
Initialization error label was added

Pla 2711 initialization error on panel

---

js/script.js

PLA-2711 fix for counter

---

css/audit.css
index.html
js/audit.js
tmp-data/tmp1.json

PLA-2750 suppressions retrieved from report

---

index.html
js/audit.js
tmp-data/tmp1.json

3 tasks were done:
- support for new json structure was added
- logic for calculating fully suppressed violation was fixed
- disabled and passed violations are now displayed for any sorting

Pla 2335 new json structure support

---

css/audit.css
index.html
js/audit.js
js/deploy.js
js/script.js
js/static-map.js
tmp-data/tmp1.json

Displaying old resources in audit and map view

Pla 2569 opacity for old resources

---

js/script.js
js/static-map.js

Suppressions removed form map
Cloudcoreo region is displayed correctly when new resources are received

Pla 2851 hide suppressions from map

---

js/audit.js

create suppression_expired for audit-resources

create suppression_expired for audit-resources

---

js/script.js
js/static-map.js

Alerts which were marked as non-violations are displayed on map as cloud objects

PLA-3116  Inventory data displayed on map

---

js/audit.js

PLA-3433 resources tab is selected automatically when no audit resources were provided

---

js/audit.js

It can be tested locally or once PR for saving plan globals will be merged

PLA-3388 disable_disabled_card_processing check was added

---

css/audit.css
css/map.css
index.html
js/audit.js
js/script.js

Reverts CloudCoreo/default-panel#116

Revert "merge in dev"

---

css/audit.css
css/map.css
index.html
js/audit.js
js/script.js

Reverts CloudCoreo/default-panel#117

Revert "Revert "merge in dev""

---

index.html
js/audit/AuditRender.js
js/audit/AuditUI.js
js/audit/audit.js
js/configs/constants.js
js/configs/uiTexts.js
js/map/static-map.js
js/pie.js

Fixed view with all checks are passed. 
If there are no disabled violations, success message will be displayed. 
But I think that this message should be also visible if we have only informational rules with cloud objects

PLA-3729 fix for no violations views

---

js/audit/audit.js
js/configs/constants.js
js/script.js

Reverts CloudCoreo/default-panel#131

Revert "dev to master"

---

js/audit/audit.js

bug fix ex: alert.level = 'low'  || alert.level='Low'  || alert.level = 'loW'

PLA-4598 added capitalization of property for alert obj

---

js/audit/AuditUtils.js

Everything will work as expected if suppression_until date is null, undefined or empty string

PLA-5110 fixing checkIfResourceIsSuppressed function.
